### ISSUE TITLE
Questions: is reveal-hugo primarily for stand-alone slides? Is it practical to embed in a page template?

### ISSUE THREAD

**Issue by julianrendell** [dzello/reveal-hugo#100]
Hi, thanks for creating what looks to be a very powerful and convenient tool!

I'd like to verify my understanding about what reveal-hugo  is for, and ask for guidance as to if one of my use cases is pushing far enough out of it's intended use as to probably be problematic for me to develop and maintain.

Am I correct that the primary goal of reveal-hugo is to create reveal.js slides and not for embedding reveal.js into a Hugo site? i.e the goal is more to use Hugo's templating etc to make it easier to make reveal.js compliant input/html files than it is to add a reveal.js set of slides to an (existing) Hugo site?

If the above is correct then my first use case (to generate slides for teaching classes) is a great fit.

My second use case is to replace an aging Pelican based site, which has become difficult to update and maintain (too many plugins and a heavily customized theme...) The site needs to have a menu bar at the top of the screen and a column of social-media widgets down the right for all pages. I think I understand enough about the Hugo theming to be able to make a template that could do this, and have the page content appear in a central "content box" in the template.

It would be amazing to use reveal.js slides as the content on some pages!

Is it possible to configure reveal-hugo to generate embedded slides that could be used with a template page that set the `.reveal` root element as per https://revealjs.com/initialization/#multiple-presentations?

How would you get the generated reveal.js compatible content into the template described above?

Is this likely to be fragile? Ie would I be better to use a tool like blocs to create the layout, generate the reveal.js slides using reveal-hugo, and then manually mash them together? (The site doesn't need to be updated too often, and I can write scripts to help do the mashing.)

Thanks in advance for suggestions and advice!

**Comment by dzello** [comment]
@julianrendell Thanks for asking your questions and welcome to the project.

reveal-hugo does work well to embed slides in an existing Hugo site, but it expects that the slides are the whole page. So it's more like hosting slides on a Hugo site vs. embedding them. 

That said, for your use case, I do think you could accomplish this by adding HTML to the layout per the instructions here: https://github.com/dzello/reveal-hugo#adding-html-to-the-layout. That would let you add a header, a footer, and anything else you need. I think the Reveal.js presentation might try to take up the whole page still, but you could apply some CSS to the `.reveal` element to shrink it by some factor. I've never tried this but it seems possible in theory.



I'm not sure how easy it will be to add 2 Reveal.js presentations on the same page. reveal-hugo only knows how to work with one Reveal object. The workaround would be to add custom JavaScript and HTML which is possible but not very elegant.
