### ISSUE TITLE
 Your theme's demo is not working on the Hugo Themes website

### ISSUE THREAD

**Issue by onedrawingperday** [dzello/reveal-hugo#11]
Hello @dzello your theme's demo is [not generating](https://themes.gohugo.io/reveal-hugo/) 

When I test your theme's Example Site I get the following ERROR:

```
Error: Error building site: "/hugoThemes/reveal-hugo/exampleSite/content/home/shortcodes/slide.md:178:1": failed to render shortcode "section": "/hugoThemes/reveal-hugo/layouts/shortcodes/slide.html:26:33": execute of template failed: template: shortcodes/slide.html:26:33: executing "shortcodes/slide.html" at <index . $template>: error calling index: cannot index slice/array with type string

```

Can you please look into it?

Thank you.

CC / @digitalcraftsman

**Comment by dzello** [comment]
Thanks for the report. Something in Hugo 0.5.0 broke it, investigating now.

**Comment by dzello** [comment]
Fixed with cc282af. It looks like some usage of slice and .Scratch was working as far as Hugo 0.48 but not in 0.50. The example site should build now, let me know if there are any issues.

**Comment by onedrawingperday** [comment]
Thank you for the swift reply @dzello 

I confirm that now your theme's demo is generated when I execute the Build Script.

This will be reflected on the Hugo website the next time themes are updated.

Thanks.

**Comment by dzello** [comment]
@onedrawingperday Absolutely, good to know it's building now, thanks!

**Comment by digitalcraftsman** [comment]
Thanks Josh for fixing this issue. I'll update the themes soon.
