### ISSUE TITLE
No mermaid graph rendered

### ISSUE THREAD

**Issue by nicolasfara** [dzello/reveal-hugo#126]
Hi
I have an issue with mermaid in rendering a graph.

This is the slide:
```
OTHER SLIDES...

{{% section %}}

# Digital Twin Models

---

# Milk Tank Model

{{< mermaid >}}
graph LR
    A --> B
    B --> C
{{< /mermaid >}}

{{% /section %}}
```

But the graph is not rendered.

Note: I used mermaid also for other projects using `reveal-hugo` and everything worked as expected.

![Screenshot_20221105_121952](https://user-images.githubusercontent.com/11615611/200117351-905aa5fa-9172-445d-9d0b-900e4c024135.png)

This issue could be related to the last work made by @davidovich on mermaid?

**Comment by davidovich** [comment]
Hi @nicolasfara 

I have tried to reproduce your error with no avail. Tried in latest Chrome and Firefox. The "latest work" you mention was related to:

1) At hugo build-time, download the latest mermaid.js as a local resource, and use the local version once the site is built
2) ensure that when landing on a mermaid enabled page, that the render occurs.

I added your code to the exampleSite, and was not able to reproduce. Note that the browser may have cached a prior version of your site, maybe a forced reload would fix that ?

**Comment by nicolasfara** [comment]
Hi @davidovich
I think I fixed the problem: all the slides are inside the `_index.md` file and the mermaid diagram does not work.
So I moved all the slides inside another file (and directory) and all the mermaid diagrams now work.

The structure of the `content` folder is as follows:
```
home/
├─ slides.md
_index.md

```
In conclusion, if all the slides are in the `_index.md` file, the mermaid diagrams do not work.
If the slides are on a different file, all the diagrams are rendered correctly.

**Comment by davidovich** [comment]
Ok, this brings me some ideas. 
The automated evaluation of the need for mermaid is based on iterating `.Site.RegularPages` and it seems that root pages are not included in that slice. I think using `.Site.AllPages` instead would solve it for your specific structure (and should be supported).
