### ISSUE TITLE
small glitch in reusable slide inclusion code

### ISSUE THREAD

**Issue by davidovich** [dzello/reveal-hugo#141]
If you currently navigate to https://reveal-hugo.dzello.com/#/40/1, you'll notice that the `slide` shortcode with `content=` usage example is not displayed. I believe this is because the shortcode is being rendered on [itself](https://github.com/dzello/reveal-hugo/blob/master/exampleSite/data/home.toml#L29). Since the intent is to document how the code should be written, we should escape rendering in that example.

There is another instance of this in [common.nested](https://github.com/dzello/reveal-hugo/blob/master/exampleSite/data/common/nested.toml#L15).

**Comment by dzello** [comment]
@davidovich Good catch, appreciate the fix 🙏
