### ISSUE TITLE
Reveal Theme Demo on Hugo website contains 3rd party tracking

### ISSUE THREAD

**Issue by onedrawingperday** [dzello/reveal-hugo#15]
Hello again @dzello 

Currently I am one of the maintainers of the [Hugo Themes](https://github.com/gohugoio/hugoThemes/) repository.

Recently I audited the Hugo Themes website and it has [come to my attention](https://github.com/gohugoio/hugoThemes/issues/535) that your theme's demo has third party tracking enabled.

```
     \reveal-hugo\exampleSite\layouts\partials\reveal-hugo\body.html:
        <script async src="https://www.googletagmanager.com/gtag/js?id=UA-24132749-1"></script>
        <script>
         window.dataLayer = window.dataLayer || [];
         function gtag(){dataLayer.push(arguments);}
         gtag('js', new Date());
         gtag('config', "UA-24132749-1");
        </script>
```

Can you please remove the Google Tag Manager tracking script?

Once you look into this please let me know.

Thank you!

**Comment by dzello** [comment]
I've gone ahead and removed the code in [this commit](https://github.com/dzello/reveal-hugo/commit/c3a0ca09bcef123afa5a238db6bbfd4ba7815c45). Let me know if there are any further issues.
