### ISSUE TITLE
Is it possible to make a two-column slide?

### ISSUE THREAD

**Issue by axiomtutor** [dzello/reveal-hugo#153]
Is it possible to make slides with two-column components?  For instance, if a bullet list runs long, can it be redirected to a second column in the slide?  Thanks!

**Comment by davidovich** [comment]
Hi, you have full control on the css that is applied to the slide. See an [example for side by side](https://reveal-hugo.dzello.com/#/43) icons. Using that technique, I think you can achieve the same result for bullet lists.

**Comment by mayankguptadotcom** [comment]
@axiomtutor - i've created a [shortcode](https://github.com/mayankguptadotcom/slides/blob/main/layouts/shortcodes/container_columns.html).

and in your markdown file you can use it like this

```
{{< container_columns "100%" "left" "10px" >}}
- Template Layouts
- Event Layouts
- Design Tips
- Design Elements
- Product Logos
- Speaker Slides
----  <!-- Separator between columns -->
- Window Slides
- Charts, Tables, & More
----  <!-- Separator between columns -->
- Window Slides
- Charts, Tables, & More
{{< /container_columns >}}
```

Here `----` (four dashes) can be used as the delimiter to create multiple columns. Hope this helps.

**Comment by dzello** [comment]
@mayankguptadotcom Thanks for sharing your shortcode 🙏

**Comment by mayankguptadotcom** [comment]
@dzello - Happy to help the community as much as I can.

**Comment by dzello** [comment]
@mayankguptadotcom We appreciate it, thank you! 🙏
