### ISSUE TITLE
IE browser support

### ISSUE THREAD

**Issue by solrayc** [dzello/reveal-hugo#20]
I just stumbled upon an issue with viewing reveal-hugo in IE11.

Nothing renders on page and the page stays blank, except for custom HTML.
Compability view reveals full presentation vertically with no ability to scroll.

This issue is present on my localhost and on reveal-hugo demo page.

[revealjs.com](https://revealjs.com/) renders fine in IE.
[reveal-hugo demo](https://themes.gohugo.io/theme/reveal-hugo/) does not render in IE.

[There is](https://github.com/hakimel/reveal.js/wiki/Browser-Support) IE support for revealjs.

**Comment by dzello** [comment]
Thanks for reporting. I'll look at this in the next few days.

**Comment by dzello** [comment]
I believe this was the root cause: https://github.com/mathjax/mathjax-v3/issues/87

I added the classList polyfill to the Reveal.js plugins. Can you try the [reveal-hugo](https://reveal-hugo.dzello.com/) again?

**Comment by solrayc** [comment]
Still does not work, unfortunately.
Updated the theme and tested it locally on `hugo server` , and tested it on live website.
Did test [reveal-hugo](https://reveal-hugo.dzello.com/) as well.
Tested with two different windows machines.

Here is my IE 11 console log for [reveal-hugo](https://reveal-hugo.dzello.com/)
```
DOM7011: The code on this page disabled back and forward caching. For more information, see: http://go.microsoft.com/fwlink/?LinkID=291337
reveal-hugo.dzello.com
HTML1300: Navigation occurred.
reveal-hugo.dzello.com
HTML1509: Unmatched end tag.
reveal-hugo.dzello.com (624,29)
HTML1509: Unmatched end tag.
reveal-hugo.dzello.com (649,48)
HTML1509: Unmatched end tag.
reveal-hugo.dzello.com (661,46)
HTML1509: Unmatched end tag.
reveal-hugo.dzello.com (680,46)
HTML1509: Unmatched end tag.
reveal-hugo.dzello.com (685,46)
SCRIPT438: Object doesn't support property or method 'assign'
reveal-hugo.dzello.com (934,3)
```

Here is whats on line 934 in `SCRIPT438: Object doesn't support property or method 'assign'
reveal-hugo.dzello.com (934,3)`
```
  var options = Object.assign({},
    camelize(revealHugoDefaults),
    camelize(revealHugoSiteParams),
    camelize(revealHugoPageParams));
  Reveal.initialize(options);
  hljs.initHighlightingOnLoad();
</script>
```

Hope it helps.

**Comment by dzello** [comment]
Turns out IE11 doesn't support `Object.assign` so I had to implement a polyfill. Pull the latest code and give it another try?

**Comment by solrayc** [comment]
Everything works! You fixed it. This is magic, thank you sir!
Works in IE11 and in emulated IE10, IE9 as well.
Again, a billion thanks!

**Comment by dzello** [comment]
Ok great, thank you for reporting!
