### ISSUE TITLE
background-video-loop doesn't work

### ISSUE THREAD

**Issue by cr-chsn1** [dzello/reveal-hugo#24]
The video-loop doesn't seem to work.
While background-video works great, background-video-loop only shows me a blank background.

Is there something special with a looping background video or if
{{< slide background-video="/videos/video.mp4" >}}
is working
{{< slide background-video-loop="/videos/video.mp4" >}}
should be working, too?

**Comment by dzello** [comment]
According to this [SO question](https://stackoverflow.com/questions/28780825/how-the-loop-the-data-background-video-in-reveal-js) here's what I think you might need:

{< slide background-video="/videos/video.mp4" data-background-video-loop="loop" >}}

Not the most obvious on the Reveal.js side 🤷‍♂️
