### ISSUE TITLE
Templates don't work when defined in `config.toml`

### ISSUE THREAD

**Issue by DanielJonesEB** [dzello/reveal-hugo#26]
Hi,

I'm getting an error message when trying to use a slide template on Hugo 0.54.0. Using the latest commit on `master` of this repo at time of writing (can't figure out the exact one, as I did a subtree pull).

`config.toml` has this:

```
[params.reveal_hugo.templates.title]
class = "title"
background = "#1D74BC"
```

Markdown file is thus:

```
+++
title = "Overview"
outputs = ["Reveal"]
weight = "10"
+++

{{< slide id="overview" template="title" >}}

```

Error is:

```
ERROR 2019/03/05 18:12:58 "/Users/deejay/workspace/k8s-course/slides/content/home/state.md:7:1": failed to render shortcode "slide": failed to process shortcode: "/Users/deejay/workspace/k8s-course/slides/themes/reveal-hugo/layouts/shortcodes/slide.html:1:1": execute of template failed: panic in Execute: reflect: call of reflect.Value.Type on zero Value. See "https://github.com/gohugoio/hugo/issues/5327" for the reason why we cannot provide a better error message for this.
Total in 29 ms
Error: Error building site: "/Users/deejay/workspace/k8s-course/slides/content/home/overview.md:7:1": failed to render shortcode "slide": failed to process shortcode: "/Users/deejay/workspace/k8s-course/slides/themes/reveal-hugo/layouts/shortcodes/slide.html:1:1": execute of template failed: panic in Execute: reflect: call of reflect.Value.Type on zero Value. See "https://github.com/gohugoio/hugo/issues/5327" for the reason why we cannot provide a better error message for this.
```

The issue is here: https://github.com/dzello/reveal-hugo/blob/master/layouts/shortcodes/slide.html#L24

`($.Site.GetPage $.Page.Section).Params.reveal_hugo.templates` is nil if one has put the template definition in `config.toml`, which is a supported use case according to https://reveal-hugo.dzello.com/#/36/1

I've worked around this by changing the shortcode, so there's no rush for a fix in my case, but maybe other users will encounter this.

Thanks for all the hard work, I've generally had a good experience with the theme and we use it for creating presentations as part of training courses.

**Comment by dzello** [comment]
Cool to hear you're using the theme for making training courses!

I haven't been able to reproduce the bug yet. If you check out the [template-example presentation]() in this repo, it's using a template from config.toml. It looks like the shortcode breaks when a template is used from within a page that doesn't have a section associated to it, when `($.Site.GetPage $.Page.Section)` returns nil.

Can you share a bit about your content structure and where you're calling the slide shortcut from? Thanks!
