### ISSUE TITLE
Mathsjax support

### ISSUE THREAD

**Issue by Crown421** [dzello/reveal-hugo#28]
I am currently trying to extend this wonderful project to serve me well during the rest of my PhD, 
so I am attempting to include mathjax to be able to render equations. 

However, I am struggling a bit (partly because I have almost no webdev experience). 

I have attempted two things:
1. Adding support via hugo
First I added the script from [here](https://divadnojnarg.github.io/blog/mathjax/) as a partial, and then added `{{ partial "layout/mathjax_support.html" . }}` in `baseof.reveal.html`.
This works, however I don't like that it is always on, and would like to do it properly to be enabled/ disabled via parameter. 

2. Loading the math.js plugin via reveal. 
Adding 
`<script type="text/javascript" src="{{ printf "%s/plugin/math/math.js" $reveal_location | relURL }}"></script>`
to the `javascript.html` should have enabled the plugin, and then allow me to render
```
{{< markdown >}}
## Math Support
  `\\() J(\theta_0,\theta_1) = \sum_{i=0} $\\)`
{{< /markdown >}}
```
but unfortunately this does not work. 

I think I would prefer the first option, as it does not require the markdown shortcode in addition to the backticks, but am unclear on how to make his parameterizeable via the _index.md. 
At the same time, I would like to add the option to add plugins from the standard reveal plugin location, which I will do once I understand why loading the math.js plugin seems to fail. 

Thank you for your time and this project, I hope to contribute more in the future.

**Comment by dzello** [comment]
Thanks for opening the issue @Crown421. I should have time in the next few days to look into this. In the meantime, did you see the [plugin-example presentation](https://reveal-hugo.dzello.com/plugin-example/#/)? That might hold some of the clues to get this to work.

**Comment by dzello** [comment]
See also the code behind that presentation here: https://github.com/dzello/reveal-hugo/tree/master/exampleSite/content/plugin-example

**Comment by Crown421** [comment]
Very sorry, the mistake was not actually any of the 3 attempts that I made, but instead that my noscript blocked cloudflare and hence also the remote mathjax. 
It got it working now with your generic example, and also learned a lot about how this works. 

So, close I think?

**Comment by dzello** [comment]
Ok great, good to hear! 🎉

**Comment by mbhall88** [comment]
FWIW I got maths working by adding the following to `layouts/partials/reveal-hugo/body.html`

```html
<script>
MathJax = {
  tex: {
    inlineMath: [['$', '$'], ['\\(', '\\)']]
  },
  svg: {
    fontCache: 'global'
  }
};
</script>
<script type="text/javascript" id="MathJax-script" async
  src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-svg.js">
</script>

```

And then you can just do this in a slide

```md
## Cool equations

Displayed equations are wrapped in double-\$

$$\frac{n!}{k!(n-k)!} = \binom{n}{k}$$  

Inline equations like $E=mc^2$ are wrapped in single-\$
```

## Example

<img width="2331" alt="maths" src="https://user-images.githubusercontent.com/20403931/78510202-8a240f80-778b-11ea-90ca-dc8d2f6ef3a7.png">

The repo with this code in it is my nordtheme template [here](https://github.com/mbhall88/reveal-hugo-nord).

**Comment by dzello** [comment]
@mbhall88 That's great! I'll add it to the docs.
