### ISSUE TITLE
Section shortcode does not work in Hugo 0.55

### ISSUE THREAD

**Issue by robertmarkbram** [dzello/reveal-hugo#29]
See https://discourse.gohugo.io/t/vertical-sections-not-displaying/18280, which had me bashing my head against my poor keyboard for a while... 

The `section` shortcode has been modified in hugo and needs to be updated in the reveal-hugo theme.

Rob
:)

**Comment by dzello** [comment]
Thanks for opening the issue @robertmarkbram, I'll investigate.
