### ISSUE TITLE
Sections not joined to index

### ISSUE THREAD

**Issue by pganssle** [dzello/reveal-hugo#3]
Even with `outputs=["Reveal"]` in sub-sections, I am finding that `hugo new` is not merging the content sections into a single presentation for some reason.

Here is a bash script that creates a test repository:

```bash
hugo new site test-reveal
cd test-reveal
git init .
git submodule add git@github.com:dzello/reveal-hugo.git themes/reveal-hugo

# Create the config.toml
cat >> config.toml << EOF
theme = "reveal-hugo"
disableKinds = ["sitemap", "RSS", "categories"]

[outputFormats.Reveal]
baseName = "index"
mediaType = "text/html"
isHTML = true
EOF

mkdir -p content/section

# Create the main content
cat > content/_index.md << EOF
+++
title = "My presentation"
outputs = ["Reveal"]
+++

# Test

This is an example
EOF

# Create a section
cat > content/section/_index.md << EOF
+++
title = "Subsection"
outputs = ["Reveal"]
+++

# Subsection

This is a section
EOF
```

Once created, running `hugo` creates two separate presentations:

```bash
$ hugo

                   | EN  
+------------------+----+
  Pages            |  2  
  Paginator pages  |  0  
  Non-page files   |  0  
  Static files     |  2  
  Processed images |  0  
  Aliases          |  0  
  Sitemaps         |  0  
  Cleaned          |  0  

Total in 8 ms
$ tree public
public
├── index.html
├── reveal-hugo
│   └── plugin
│       └── notes
│           ├── notes.html
│           └── notes.js
└── section
    └── index.html

4 directories, 4 files

```

As you can see, the `section` folder is still generated. Any idea what went wrong? Is this some behavior that maybe changed in hugo?

I'm using Arch Linux, hugo version:

```bash
$ hugo version
Hugo Static Site Generator v0.42.1 linux/amd64 BuildDate: 2018-06-13T20:49:30+0200
```

**Comment by dzello** [comment]
Thanks for the report!

To be added to the root presentation, the section name has to be `home`. So the folder name in `content` will be `home`, not `section` per above. Within the home folder, you won't need another `_index.md`, you can start adding Markdown files rightaway that represent the sections of your presentation, e.g. `introduction.md`, `conclusion.md`, and so on.

Let me know if that clears things up. This is definitely an area where I think the doc could be improved.

**Comment by pganssle** [comment]
@dzello Thanks for the clarification. Maybe this is hugo-specific terminology, but what is [this](https://dzello.com/reveal-hugo/#/13) referring to?

**Comment by dzello** [comment]
In that example section is in `{}` because it's meant to be replaced with a folder name that represents your content (in this case the name of a separate presentation). It is a bit of a Hugo thing I suppose, as that's how Hugo wants you to organize your content (into sections, with the name of the section coming from what you call the folder). Here's some background on [Hugo sections](https://gohugo.io/content-management/sections/).

Let's say you had 2 presentations you wanted to host from one Hugo site, one at the root and one in a section, maybe slides from a TED Talk. You might have a tree like this:

```
- content
  - home
    - body.md # a chunk of the root presentation
    - conclusion.md # another chunk of the root presentation
  - _index.md   # start of the root presentation
  - ted-talk
    - _index.md # start of ted talk presentation
    - body.md # a chunk of the ted talk presentation
    - conclusion.md # another chunk of the ted talk presentation
```

**Comment by pganssle** [comment]
Ah, OK. So then the behavior I observed (where two separate presentations are created) is expected. I'll leave it to you whether to close this issue or leave it open until changes are made to the documentation. Thanks!

**Comment by dzello** [comment]
Updated the docs, thanks!
