### ISSUE TITLE
Navigation breaks when using more than one shortcode in same slide

### ISSUE THREAD

**Issue by ccamara** [dzello/reveal-hugo#33]
Provided the following code:

```markdown
+++
title = "My title"
description = ""
outputs = ["Reveal"]

[reveal_hugo]
theme = "white"

[reveal_hugo.templates.bg-dark]
class = "bg-dark"
background = "#000"

+++

{{< slide template="bg-dark" >}}
{{< slide background-image="https://reveal-hugo.dzello.com/images/alex-litvin-790876-unsplash.jpg" >}}

## Slide one


---

## Slide 2

This should appear on the right, not below the previous one.

```

All slides after slide 1 appear below slide 1, instead of appearing on the right, as expected (unless creating a section, but that's not the case). The problem is solved whenever I comment one of the shortcodes I am using, but unfortunately, I need both of them (at least!).

**Comment by dzello** [comment]
Thanks for opening the issue @ccamara. Having two slide shortcodes one after the other is not supported (creating another section tag is what would happen, which is what you're seeing). Instead, you can put `template="bg-dark"` inside of the second shortcode and delete the first. Each `slide` shortcode can have multiple attributes. Let me know if that helps.

**Comment by dzello** [comment]
For clarity, this is what it would look like:

```
{{< slide template="bg-dark" background-image="https://reveal-hugo.dzello.com/images/alex-litvin-790876-unsplash.jpg" >}}

## Slide one
```

**Comment by ccamara** [comment]
Oh, didn't know that multiple attributes can be added within same shortcode. Even better, as it is much more concise!

PS: it is working now, as expected.
PS2: thanks for the great job.
