### ISSUE TITLE
Missing reveal's data-background-opacity property

### ISSUE THREAD

**Issue by ccamara** [dzello/reveal-hugo#34]
I am new to reveal-hugo, and I may be missing some things, but I could not figure out how can I use reveal's `data-background-opacity`property.

I have tried to use it within a shortcode `{{< slide background-image="img/whatever.jpg" data-background-opacity="0.3">}}` or even within a template in _index.md toml's, without success

```markdown
[reveal_hugo.templates.bg-dark]
class = "bg-dark"
background = "#000"
data-background-opacity = "0.3"
```

Am I missing something?

**Comment by ccamara** [comment]
After reading again `readme.md` I found the solution was there:

> You can also pass through your own, a data- prefix will be added automatically to each one (except for id and class).

So, simply editing my code to get rid of `data-` worked perfectly: `{{< slide background-image="img/whatever.jpg" background-opacity="0.3">}}`, as expected.

Closing the issue. Sorry for the inconvenience.

**Comment by dzello** [comment]
No worries! It's better to open it when you're not sure, as some others may also be having the issue. Glad this was an easy one to resolve.
