### ISSUE TITLE
Failing to use a custom scss theme

### ISSUE THREAD

**Issue by ccamara** [dzello/reveal-hugo#35]
TLDR: I created a custom scss theme but hugo can't compile it. Probably because it doesn't find mixins.

I want to use a custom scss theme on my slides (in fact I would like to create several of them) so I did the following:

1. Add the following lines to my frontmatter:

```
[reveal_hugo]
custom_theme = "custom-theme.scss"
custom_theme_compile = true
```
2. Created the file `assets/custom-theme.scss` with the following content:

```scss
// Default mixins and settings -----------------
@import "../template/mixins";
@import "../template/settings";
// ---------------------------------------------



// Override theme settings (see ../template/settings.scss)

// My scss properties here

// Theme template ------------------------------
@import "../template/theme";
// ---------------------------------------------

```
3. When running `hugo-serve` I get the following error:

> error: failed to transform resource: SCSS processing failed: file "stdin", line 10, col 1: File to import not found or unreadable: ../template/mixins. 

What am I doing wrong? My guess is that the `@import` routes are wrong, but I am not sure where should I point them.

**Comment by dzello** [comment]
I bet it is the import routes. There's a custom theme example in the repo that might be helpful to look at:

https://github.com/dzello/reveal-hugo/blob/master/exampleSite/assets/custom-theme.scss

The imports there look like this:

```scss
@import "reveal-js/css/theme/template/mixins";
@import "reveal-js/css/theme/template/settings";
```

**Comment by ccamara** [comment]
Thanks, that was it! I changed to those paths (didn't know how to write it accordingly, as I was also including `assets` before) and it's compiling perfectly.
