### ISSUE TITLE
Footnotes do not link properly

### ISSUE THREAD

**Issue by samtsai** [dzello/reveal-hugo#4]
I am trying to apply footnotes via [Blackfriday's](https://github.com/russross/blackfriday) implementation.

```
This is a footnote.[^1]

[^1]: the footnote text.
```

The markup is correctly rendered but clicking on the links always takes me back to the start of the presentation instead of the reference.

**Comment by dzello** [comment]
Thanks for opening an issue. Can you share the HTML that gets generated from that Markdown?

**Comment by samtsai** [comment]
The footnote in context is rendered:
```
<sup class="footnote-ref" id="fnref:1"><a href="#fn:1">1</a></sup>
```

Then a final section is auto generated:
```
<ol>
<li id="fn:1">Footnote text
 <a class="footnote-return" href="#fnref:1"><sup>[return]</sup></a></li>
</ol>
```

The `id`s and `href`s match appropriately but something seems to prevent the browser from finding the associated `id`s. As I'm looking at this further, I wonder if the routing system is interfering/doesn't support in-page anchors.

**Comment by samtsai** [comment]
Also the footnote generation completely breaks other sections that have lesser weight by rendering them outside of the `.slides` element.

![screenshot 2018-07-10 16 00 59](https://user-images.githubusercontent.com/225526/42534426-b1514486-845a-11e8-8e71-4662cc45af73.png)

**Comment by dzello** [comment]
For the issue of footnotes breaking other sections, I was able to narrow that down to the fact that footnote generation [adds an `<hr />` to the DOM](https://discourse.gohugo.io/t/footnote-styling/114), which reveal-hugo interprets as a new slide that ends up containing malformed HTML. I pushed a fix to detect that condition and remove the `<hr />`. You can now have sections that come later, but be advised that the footnotes slides will appear before those sections. Currently there's no way to send them to the very back of the presentation other than with JavaScript or putting the whole presentation in one section.

As far as the links, that's difficult given the nature of Reveal.js and how it controls the relationship between the URL and the DOM. Simple anchors won't work as Reveal.js doesn't keep a map of what anchor is in what slide (i.e Reveal.js doesn't know what slide `#fn:1` is so it can't go back there automatically). The best you could do is rewrite the links to point to the slide where you know the content is using JavaScript after the page loads.

Your other option is to just create footnote links manually in a slide at the end of the presentation, which all things considered might be easier given these limitations.

**Comment by samtsai** [comment]
Thanks @dzello for the follow up and fix for the footnote generation. Verbally confirming it no longer breaks the slides 👍 

And for the links, I totally get it.  One of the alternatives will probably work fine. Thanks!

**Comment by dzello** [comment]
Thanks for the confirmation 👍
