### ISSUE TITLE
Markdown in notes

### ISSUE THREAD

**Issue by ccamara** [dzello/reveal-hugo#40]
Currently noes do not support markdown (or I haven't figured out how to use it). Following code renders `*` instead of formatting the text.

```
{{% note %}}
You found the **speaker notes!**
{{% /note %}}
```

**Comment by dzello** [comment]
Thanks for logging the issue. It looks like that should be rendering the markdown as you expect, I'm not sure why it isn't. I'll give it a look this weekend.

**Comment by ccamara** [comment]
great!
