### ISSUE TITLE
Font Size

### ISSUE THREAD

**Issue by Arsur** [dzello/reveal-hugo#42]
How can i change the font size. I just found the `<small>` Tag, but this destroys my markdown.

**Comment by ccamara** [comment]
Font size, amongst all styles that define how your slide look like are stored on a scss file named like your current theme, defined in _index.md toml.  

While those files can be changed, it is advised to create a custom theme instead, where you can define all your properties.

Please refer to official documentation here: https://reveal-hugo.dzello.com/#/11 (and following slides to see how custom themes work).
