### ISSUE TITLE
vertical adjust to space

### ISSUE THREAD

**Issue by nocquidant** [dzello/reveal-hugo#46]
Thank you for your great work!

Is there a simple way to adjust slides vertically. Some of my slides have quite a lot of text and also images, and I would like to be able to write them "productively" ie without having to resize my images and reduce my text (which I know is probably a good thing).

Thanks,
nick

**Comment by dzello** [comment]
You're welcome!

Unfortunately there's no automatic way I know of to do this with reveal-hugo or Reveal.js. You could try creating a theme or adding custom CSS to achieve the effect you want.
