### ISSUE TITLE
regression with hugo v0.58

### ISSUE THREAD

**Issue by valvin1** [dzello/reveal-hugo#49]
hi, 

i'm having regression using hugo v0.58 but i can't see any error message.

symptom is it opens well the first slide but doesn't load the next and controls doesn't appear.

on three different projects 2 are broken and 1 is working but i've not yet seen what is the difference.

what about yours ?

thank you :)

**Comment by valvin1** [comment]
i reproduce the issue with exampleSite

**Comment by chatziko** [comment]
Same issue here, try PR #51.

**Comment by valvin1** [comment]
@chatziko thank you it works for me.
