### ISSUE TITLE
background-iframe not showing in browser (localhost)

### ISSUE THREAD

**Issue by tabroughton** [dzello/reveal-hugo#56]
I have a slide that I would like a webpage to load in the background.  The snippet of markdown is:

```
---

{{< slide background-iframe="https://asciinema.org/a/268429?speed=10" >}}

# Installing Arduino

---
```
But the iFrame isn't showing in my browser.

I'm running hugo locally while I create my slide deck and I'm using firefox (69).

I can see the source of the page has this section:

```
<section data-noprocess data-shortcode-slide
      data-background-iframe="https://asciinema.org/a/268429?speed=10">
  

<h1 id="installing-arduino">Installing Arduino</h1>

</section>
```

and using webdeveloper tools in the console I can see the get request for the page

```
GEThttps://asciinema.org/a/268429?speed=10
[HTTP/2.0 200 OK 333ms]

Request URL:https://asciinema.org/a/268429?speed=10
Request method:GET
Remote address:109.107.38.78:443
Status code:
200
Version:HTTP/2.0
```

I can't see why my iframe isn't showing the webpage in the background

But maybe there's in issue with it? or running from localhost?

Is this an issue with firefox or am I doing something wrong?

**Comment by dzello** [comment]
Sorry about the delay in responding here. `asciicinema.org` doesn't allow iframe embedding outside of its own site. You should be able to confirm this from within the web console:

```
Refused to display 'https://asciinema.org/a/268429?speed=10' in a frame because it set 'X-Frame-Options' to 'sameorigin'.
```
