### ISSUE TITLE
vscode extension for reveal-hugo

### ISSUE THREAD

**Issue by chatziko** [dzello/reveal-hugo#57]
I created a vscode extension for reveal-hugo:

https://marketplace.visualstudio.com/items?itemName=chatziko.vscode-reveal-hugo

It allows to preview a presentation within vscode (via hugo server), and keeps the cursor synced to the current slide (both ways).

Only tested on linux. Feel free to give it a try and send comments.

__Update__: backwards sync now works out of the box, no special config is needed.

**Comment by dzello** [comment]
That's so cool! I'm a VSCode user and really looking forward to giving this a try in the next few days. I'll let you know if there's any feedback and then we can get it documented in the README.

Thanks! 🙏

**Comment by dzello** [comment]
@chatziko Looks good to me. Can you submit a PR that updates the docs to point to the extension?
