### ISSUE TITLE
Feature proposal - custom CSS

### ISSUE THREAD

**Issue by valvin1** [dzello/reveal-hugo#58]
I developed a feature that allow to add an additionnal CSS to modify small part of an existing theme or create new CSS class.

Today official way is to use partials and insert style inside head.html. I prefer using a separate file.

So if you add an attribute : 

```toml
[reveal_hugo]
custom_css = "css/custom.css"
```
in your `config.toml` or `_index.html` meta. It will loaded automatically that file.

It requires to copy `custom.css` in `static/css/custom.css` in the example.

@dzello what is your thought about this feature ? If I do a PR do I change also [Custom CSS Example](https://reveal-hugo.dzello.com/#/19)

Maybe if you like the idea it would be also interesting to add `custom_js` settings ?

**Comment by dzello** [comment]
Thanks for making the proposal @valvin1! I think this would be a good addition to make adding custom code more convenient and am happy to accept a PR for it.

I do think a matching `custom_js` makes sense in addition to `custom_css` if you'd like to add that too.

**Comment by valvin1** [comment]
I'll do the PR in the week to come :)

**Comment by valvin1** [comment]
thank you for merging :)
