### ISSUE TITLE
Using fragment shortcode and bullet list

### ISSUE THREAD

**Issue by valvin1** [dzello/reveal-hugo#60]
I'm not succeeding in using fragment shortcode and bullet list : 

```
{{% fragment %}}- *item* __1__ {{% /fragment %}}

{{% fragment %}}- *item* __2__ {{% /fragment %}}

{{% fragment %}}- *item* __3__ {{% /fragment %}}
```

it renders well italic and bold but it doesn't render bullet list. Is there a tip for that ?

I've made several tests using `{{<` or `*` for the bullet list but the result is always the same. 

I also need empty line which in my mind should not be expected.

**Comment by dzello** [comment]
I believe this is the same issue as in #36. This currently isn't supported although it definitely should be. I haven't looked at the effort yet but interested to get some ideas.

**Comment by valvin1** [comment]
Oh yes it is the same sorry for the duplicate.

I'll have a look if it is not too complicated to solve.

**Comment by valvin1** [comment]
duplicate with #36
