### ISSUE TITLE
Set css for a single slide

### ISSUE THREAD

**Issue by sebfischer83** [dzello/reveal-hugo#62]
Hi,

I try to make the font-size smaller for a table, but I don't find a way to set a css for that in only one special slide?

**Comment by valvin1** [comment]
Hi,

You can use slide shortcode and define a specific class to this class only. Then attaching a specific CSS using partials or customCSS.

[Shortcode slide](https://reveal-hugo.dzello.com/#/29)

[Extending the layout](https://reveal-hugo.dzello.com/#/17)

Does it answer to your need?

**Comment by sebfischer83** [comment]
Thanks that seems the solution

**Comment by dzello** [comment]
Thanks for chiming in @valvin1!
