### ISSUE TITLE
Nested list level3

### ISSUE THREAD

**Issue by nocquidant** [dzello/reveal-hugo#63]
I usually use lists with bullets for my presentation.

With 2 levels, no issue, rendering works as expected. With 3 levels however, I need more than 4 spaces for indentation. 

```
* item 1
* item 2
  * item 2a <-- 2 spaces is OK here
    * item 2ai <-- 4 spaces here is not enough, but 5 is OK
```
Any reason for that?

Thanks

**Comment by dzello** [comment]
Good question. I'm guessing it's something with Hugo and/or the Blackfriday markdown processor. reveal-hugo isn't doing any parsing of it's own there.
