### ISSUE TITLE
not compatible with hugo 0.60+

### ISSUE THREAD

**Issue by HeaDBanGer84** [dzello/reveal-hugo#65]
because hugo change Markdown-Parser form "Blackfriday" to "Goldberg" slide seperation seems to be broken ([hugo changelog](https://github.com/gohugoio/hugo/releases/tag/v0.60.0))

I'm not entirely sure how you insert the section in the markdown but your method, doesn't seem to work with the new parser.

**Comment by dzello** [comment]
Thanks for letting us know, it looks like we'll need to change how we separate slides.

**Comment by dzello** [comment]
The changes to support Goldmark aren't trivial, so for now I've added instructions to the readme on how to tell Hugo to use blackfriday instead. In the future, I hope to support Goldmark, but this feels like the best path for now.

**Comment by HeaDBanGer84** [comment]
Thanks for your reply. As i observed the error i looked into it and expected a bigger change. Is it still possible to use the  `{{< slide ...>}}` shortcode for slide seperation?

**Comment by dzello** [comment]
Yes, you can still use that to configure slides. The shortcode goes inside the `---` delimiters. See an example here: https://github.com/dzello/reveal-hugo#slide-shortcode.

**Comment by chatziko** [comment]
with
```
$ hugo version
Hugo Static Site Generator v0.62.1-A1518704/extended linux/amd64 BuildDate: 2020-01-01T17:45:13Z
```
I don't seem to have any problem with `defaultMarkdownHandler = "goldmark"`, am I missing something?

**Comment by dzello** [comment]
If you are not using the `section` shortcode you might be okay. But the whole list of what works vs. doesn't work is not known.

**Comment by chatziko** [comment]
It's likely not as bad as it looks, with the changes below the `exampleSite` works (modulo some details, see below):

https://github.com/dzello/reveal-hugo/compare/master...chatziko:hugo-0.62

Real changes:
- `fragment` and `section` should be processed after Markdown rendering
- `[markup.goldmark.renderer] unsafe = true` is needed

Weird (goldmark bug?):
- `---` fails inside code fences sometimes, not sure when

Minor incompatibility that can be worked around:
- html tags behave weird if they are too close to other content

Not sure:
- `{{< markdown >}}` doesn't work (very niche feature anyway)

**Comment by dzello** [comment]
@chatziko Thanks for digging into that. Good to know the delta isn't as big as I feared. Feel free to open a PR with those commits and we can track the upgrade there.
