### ISSUE TITLE
Setting chroma style does not work as explained in the hugo-hl-example 

### ISSUE THREAD

**Issue by prosoitos** [dzello/reveal-hugo#66]
Thanks a ton for this theme! It is totally awesome, it is exactly what I had been dreaming about for a while, and it is super well documented!!

I followed the info in the hugo-hl-example to use chroma instead of Highlight.js but I noticed that setting `pygmentsStyle = "<my-chosen-style>"` in the config.toml file does not have any effect.

In order to change the style, I had to modify the default Hugo highlight:

```
[markup]
  [markup.highlight]
    codeFences = true
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "<my-chosen-style>"
    tabWidth = 4
```

Maybe the problem is on my end, but in case others face the same issue, I thought that I would share.

**Comment by dzello** [comment]
@chatziko I know you added the highlighting support (thanks again!), do you have any ideas here?

**Comment by chatziko** [comment]
Did you also set `pygmentsCodefences = true` or just `pygmentsStyle = "..."`? The former is needed to enable highlight in Markdown code fences (at least before hugo v0.60).

I guess
```
[markup.highlight]
codeFences = true
```
is the same as `pygmentsCodefences = true`, I'm lost with all these changes...

**Comment by prosoitos** [comment]
Yes, I did set it.

(Note that all is working well for me. I just wanted to point out that I had to use the code I posted above rather than what is explained in your (great) demo.

**Comment by prosoitos** [comment]
> I guess
>
> [markup.highlight]
codeFences = true
is the same as pygmentsCodefences = true

That is also my understanding.

**Comment by dzello** [comment]
I've updated the docs in the example presentation to show the `codeFences` and `style` params insted of the older `pygments` versions. Thanks for filing the issue.

**Comment by prosoitos** [comment]
Great! Thank you!!
