### ISSUE TITLE
Is it possible to remove partials for some slides?

### ISSUE THREAD

**Issue by prosoitos** [dzello/reveal-hugo#68]
Thanks so much for this project :slightly_smiling_face: 

I set a logo to a presentation (thanks to [your great example](https://reveal-hugo.dzello.com/logo-example/#/)), but I would like to be able to remove the logo on some slides, for instance, using a slide shortcode.

So, is it possible not to have partials apply to a class defined in a shortcode?

I know how to define a class for those slides
```
{{< slide class="nologo" >}}
```
but then I don't know how to remove the partials from that class...

Thanks for the help! :slightly_smiling_face:

**Comment by prosoitos** [comment]
(Note that if there are other methods, not involving shortcodes, that would work for me too).

**Comment by dzello** [comment]
Glad you're finding the project useful @prosoitos!

This is a good question and unfortunately not that easy to solve. The partials are written out at the presentation, not the slide level. Even doing custom CSS for the slide couldn't hide a logo at a higher level in the DOM.

The easiest way to do this now might be with JavaScript. You can hide the logo when a certain slide enters and restore it after.

The JavaScript can go in the body partial like [this](https://github.com/dzello/reveal-hugo/blob/master/exampleSite/layouts/partials/home/reveal-hugo/body.html). The slide changed event is [described here](https://github.com/hakimel/reveal.js/#slide-changed-event). Based on the value of `event.indexh` you could add/remove a CSS class from the logo.

Let me know if this might work for you.

**Comment by prosoitos** [comment]
Thank you for your quick reply and for the tips @dzello!

I will give this a try and report here how things went.

**Comment by prosoitos** [comment]
OK, so, I knew absolutely nothing about JavaScript and I had to read your message 20 times and then look for some beginner JavaScript tutorial :smile: But I got something that works.

Since I am such an absolute noob with JavaScript, I am sharing here what I did in case you feel like giving me some feed-back/tips on how to do this better. While this does work, I suspect that it is a very naive approach and that there is probably much more elegant ways to go about this.

(That said, no worries if you don't have time since this does solve my problem. And I will close the issue. Thank you very much for the quick help!!! :slightly_smiling_face:)

# My super naive approach:

To get rid of the logo for slide 4, I added to my body.html (my logo has the id "logo"):
```
<script type="text/javascript">
Reveal.addEventListener('slidechanged', function(event) {
    if (event.indexh == 4) {
	document.getElementById('logo').style.display='none'
    }
    if (event.indexh == 5) {
	document.getElementById('logo').style.display='block'
    }
});
</script>
```

**Comment by prosoitos** [comment]
Actually, to avoid having to hide/unhide the logo every time it overlaps with some content, I opted to resize it right after the title slide and keep it small until the end:

```html
<script type="text/javascript">
Reveal.addEventListener('slidechanged', function(event) {
    if (event.indexh == 1) {
	document.getElementById('logo').style.width='125px'
    }
    if (event.indexh == 0) {
	document.getElementById('logo').style.width='250px'
    }
});
</script>
```

**Comment by dzello** [comment]
@prosoitos Nice work on picking up JavaScript so quickly! That implementation is right in line with what I was thinking. Glad we were able to find a solution that works.

**Comment by prosoitos** [comment]
OK. Cool. Thanks again for the help!!
