### ISSUE TITLE
support for print-pdf

### ISSUE THREAD

**Issue by shivakumargn** [dzello/reveal-hugo#7]
This is a enhancement request.
If to the URL **?print-pdf** is appended, then when print option is chosen in the browser, revealjs can print pdf. Getting this to work in hugo would be very nice.

**Comment by dzello** [comment]
Thanks for the request! This should already be supported. I was able to confirm it by visiting [https://reveal-hugo.dzello.com/?print-pdf](https://reveal-hugo.dzello.com/?print-pdf) and then launching the print dialog. Is that what you need?

**Comment by shivakumargn** [comment]
Thanks. Miss from my side.

Default url is https://reveal-hugo.dzello.com/#/

https://reveal-hugo.dzello.com/#/?print-pdf -> appending directly doesn't work
https://reveal-hugo.dzello.com/?print-pdf -> didn't realize this is what I should have tried.
