### ISSUE TITLE
image border problem 

### ISSUE THREAD

**Issue by Kwask94** [dzello/reveal-hugo#8]
Hello, I just discoverd hugo and reveal hogo and so far it was great and wonderful experince. 
thanks a lot 

I'm having a problem with image and svg border
I tried to edit the theme 

```
.reveal section img {
  margin: 0px 0px;
  background: rgba(255, 255, 255, 0.12);
  border: 0px solid #363636;
  box-shadow: 0 0 0px rgba(0, 0, 0, 0.15); }

.reveal section img.plain {
  border: 0;
  box-shadow: none; }

.reveal a img {
  -webkit-transition: all .15s linear;
  -moz-transition: all .15s linear;
  transition: all .15s linear; }

.reveal a:hover img {
  background: rgba(255, 255, 255, 0.2);
  border-color: #F3DA4C;
  box-shadow: 0 0 0px rgba(0, 0, 0, 0.55); }

```

so far it still shows the shadow and border

thanks

**Comment by Kwask94** [comment]
I use ![]() . im going to use svg on all my presentiation is there best way to embed svg 
and how can i make it full screen
thanks

**Comment by dzello** [comment]
Hi @Kwask94, thanks for opening the issue and glad you are finding the project useful!

To embed an SVG you should just be able to use normal image syntax in the markdown:

```markdown
![My SVG](/images/my.svg)
```

If you want the image to be full screen, you can set it to be the background image of a slide. I added an example of that to the documentation presentation, it's [Slide 30](https://reveal-hugo.dzello.com/#/30).

The code to put in the markdown is:

```markdown
---

{{< slide background-image="/images/alex-litvin-790876-unsplash.jpg" >}}

---
```

As for taking the border and the image off, your best friend there is the web inspector to see where those styles are coming from, possibly somewhere else in the CSS.

Hope that helps!

**Comment by Kwask94** [comment]
Thanks a lot

**Comment by Kwask94** [comment]
```
---

{{< slide background-image="/images/alex-litvin-790876-unsplash.jpg" >}}

---
```

When I used background image and transition it breaked

```
{{< slide transition="fade" transition-speed="fast" >}}
{{< slide background-image="/h-page-3.png" >}}
```

**Comment by dzello** [comment]
Try putting all three attributes in one slide shortcode, like this:

```
{{< slide transition="fade" transition-speed="fast" background-image="/h-page-3.png" >}}
```
