### ISSUE TITLE
document use for creating multiple presentations

### ISSUE THREAD

**Issue by ssbarnea** [dzello/reveal-hugo#80]
Not sure if is possible to use reveal-hugo to create multiple presentations using a single source repository to host them.

I would like to avoid having to create a new repository for each presentation I create and publish and instead to use a single repository to host multiple presentations.

**Comment by dzello** [comment]
Yes, this is possible. Each folder in the content directory is turned into its own presentation with `_index.md` as the root. If you look at the `exampleSite` folder of this repository,  you can see multiple presentations co-existing. Hopefully that's instructive as to how to get that set up.

**Comment by geekq** [comment]
After cloning the repo, `cd exampleSite`, `hugo serve` there is no list of presentations, but a single presentation is shown instead. I found its content in `/home`. Does `home` have a special meaning? Or how can we reach e.g. custom-theme-example? By knowing the url http://localhost:1313/custom-theme-example/ ? One paragraph documentation would be nice. Thanks for your great work - a single-presentation-repo already works great for me!

Is it also possible to have a reveal-hugo presentation inside some other hugo site? Having a separate git repository and build for every presentation would be too heavy. And having one hugo site for documentation, sort of wiki etc. and _separate_ hugo site just for presentations (even multiple) feels cumbersome. hugo seems to support multiple hugo themes per site but one example how to install reveal-hugo and activate just for a single content/ subfolder would be great, provided you use that approach too. Or do you have a separate git repo / hugo site just for all your presentations?

**Comment by geekq** [comment]
Finally found the source of all my trouble: while the hugo modules supposed to be modular, in our case - provide revealjs type of output, and most parts in https://github.com/joshed-io/reveal-hugo/tree/master/layouts/_default try to be a good citizen (they contain `reveal` in file name  and only take effect for sections with `output: reveal`, some nasty ones take high priority (according to the order in https://gohugo.io/templates/lookup-order/#single-templates)

The hack https://github.com/joshed-io/reveal-hugo/commit/d3e297d5ccf21e24d91a7bf61b2513f8d4b02841 just nukes all the other layout definitions you may have in your repo, provided by other theme. This is why I was getting empty pages all the time!
