### ISSUE TITLE
Firedox: Unable to start presenter mode (s): Error connecting to main window.

### ISSUE THREAD

**Issue by ssbarnea** [dzello/reveal-hugo#81]
It seems that regardless if I run from localhost or from the deployed version, when I press `s` key to enable presenter mode I end-up with:
```
Error connecting to main window.
Please try closing and reopening the speaker view.
```
I looked using Firefox inspect and found no error reported in console or network requests.

Example link https://sbarnea.com/slides/ansible-lint/#/2

Note: I had to add the always-allow pop-ups on Firefox to make it open the window.

I can confirm that this is broken only under Firefox, I tested Chrome and Safari on MacOS and they both successfully start the presenter mode.

**Comment by dzello** [comment]
Thanks for logging the issue. I can confirm it's working in Chrome.

Do speaker notes for the Reveal.js demo work for you in Firefox? https://revealjs.com/#/

**Comment by ccamara** [comment]
Speaker notes are working for me using Firefox 74.0 for ubuntu.

I can see the speaker notes from: 

* https://revealjs.com/#/
* https://reveal-hugo.dzello.com/
* https://slides.carloscamara.es/2019-10-19-collaborative-cartographies (my own slides)

**Comment by ssbarnea** [comment]
Yes they are working today! Both mine and the given example. Not sure what happened over the weekend when it did not work with Firefox.
