### ISSUE TITLE
Adding "sources" of a slide

### ISSUE THREAD

**Issue by guilhem** [dzello/reveal-hugo#88]
It can be useful to be able to add sources of what is on slides.

Examples: 
- https://devops.training.barpilot.io/implementation/#/16 "Melvin E. Conway"
- https://devops.training.barpilot.io/implementation/#/37 "https://www.slideshare.net/jesserobbins/cloud-expo-jesserobbinsopscode20130129b"

My current code is here https://github.com/guilhem/devops-training/blob/master/themes/reveal-hugo/layouts/shortcodes/source.html
but... as you see it's far from perfect as I'm not a CSS expert.

**Comment by dzello** [comment]
Thanks for opening the issue. I think this will be better left up to each user, since the positioning and text of the source can vary widely. I will close the issue but still willing to accept a PR if anyone feels strongly enough to try and add something.
