### ISSUE TITLE
Update revealjs to v. 4.0.x

### ISSUE THREAD

**Issue by ccamara** [dzello/reveal-hugo#90]
Some days ago, revealjs was updated to v.4.0.0 (and just a few hours ago to 4.0.2), would it be possible to update from 3.9.2 to this one?

Seeing this commit https://github.com/dzello/reveal-hugo/commit/9054d2b783f6dcc8b678eac9a9c1ce4721bbba64 I thought that such change would consist of replacing `/static/reveal-js` folder, but I am afraid is more complex than that.

**Comment by dzello** [comment]
Thanks for noting the upgrade, it's definitely something that would be good to do.

**Comment by ccamara** [comment]
@dzello if you provide some minima guidance, I'd love to try to do a PR myself (provided you are not working on this now, as it is likely it will take me some time, provided I've never done it and I do not have much free time in the upcoming days)

**Comment by dzello** [comment]
@ccamara That'd be really great, thanks for asking. I'll be happy to review code and answer whatever questions come up.

**Comment by ccamara** [comment]
correct me if I am wrong, but I understand that last version should be placed in `static/reveal-js`, but I'm not sure if that's right and other changes should me made as well. After all, the content structure there is not exactly the same as that of reveal-js itself.

**Comment by dzello** [comment]
We can track this over at PR #91, closing the issue here.
