### ISSUE TITLE
fragment / frag inside section does not work

### ISSUE THREAD

**Issue by bcostes** [dzello/reveal-hugo#93]
Hello,

I am having trouble making fragment and frag shortcode work inside section shortcode.
Fot instance, the following markdown :

![image](https://user-images.githubusercontent.com/18026747/88644097-d2f92e80-d0c2-11ea-80e5-04af4c936c8e.png)

will end up with this in the browser : 

![image](https://user-images.githubusercontent.com/18026747/88643827-7dbd1d00-d0c2-11ea-8c98-56e71e30766f.png)

It works perfectly outside {{% section %}} though.

Any idea ? Is it just me ?

Thanks

**Comment by bcostes** [comment]
Sorry, haven't see that similar issue was still opened.

**Comment by dzello** [comment]
Hi @bcostes, thanks for reporting. I believe this is a known issue, the same as [here](https://github.com/dzello/reveal-hugo/issues/77).

I can't say for sure but one workaround you could try is using plain HTML in those particular slides, as documented [here](https://revealjs.com/fragments/).

**Comment by neroichi** [comment]
I had the same issues

**Comment by featherbear** [comment]
Same issues here. Works for me on `0.58.2`, but breaking in `0.68.3`.

Seems to be an issue with how Hugo is parsing the generated fragment code.  
My current workaround is to turn the `fragment.html` HTML code into a one liner ...  
it seems to stop the `<` to `&lt;` escape from happening

**Comment by chrisreddington** [comment]
@dzello, @featherbear  - Am I right in thinking that this issue is now resolved by #97, so this issue could now be closed? Thanks!

**Comment by dzello** [comment]
@chrisreddington I believe so, thanks for pointing that out, I'll go ahead and close this one.

**Comment by cengique** [comment]
Seems to be back from the dead. There is no error, but fragment animation will not work within a `{{section}}`. Workaround is using an HTML `<section>` instead.
