### ISSUE TITLE
How to remove # from (https://reveal-hugo.dzello.com/#/) example url

### ISSUE THREAD

**Issue by neroichi** [dzello/reveal-hugo#95]
I'm sorry if my question is very basic to understand. But i want to know how to remove # from the url's?
Anyway, thanks for the theme.

**Comment by dzello** [comment]
You're welcome. I believe you can set `history` to false in the Reveal.js settings to accomplish that.

To do that with reveal-hugo, add the configuration in config.toml:

```toml
[reveal_hugo]
history = false
```

Let me know if this works for you.

**Comment by neroichi** [comment]
Doesn't works for me.
But i tried this and works with
```
[params.reveal_hugo]
history = false
```
It's the right way to disable the # ?
